name: Default branch workflow

on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set node version according to .nvmrc
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'

      - run: npm install
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set node version according to .nvmrc
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'

      - run: npm install
      - run: npm run test
